#!/usr/bin/env python3
"""Field-first image policy with one optional real drip-tape roll reference."""
DRIP_TAPE_ROLL_REFERENCE='https://navar-abyari.ir/wp-content/uploads/%D9%86%D9%88%D8%A7%D8%B1-%D8%A2%D8%A8%DB%8C%D8%A7%D8%B1%DB%8C-1.webp'
REFERENCE_IMAGES={'drip_tape_roll':DRIP_TAPE_ROLL_REFERENCE}
SCENES={1:"wide field-first hero photograph: cultivated soil and crop rows occupy most of the frame; genuine thin flat 20-centimeter drip tape is installed beside the rows; if a roll is present it lies naturally on the soil at the side edge of the field, unwrapped and secondary, never centered",2:"close agricultural installation view of genuine thin flat black drip tape unwinding naturally from a modest roll placed beside a crop row; integrated emitters have 20-centimeter spacing; field and installed tape remain clearly visible",3:"accurate irrigation head unit beside a cultivated field with filter, regulator, round black polyethylene main pipe, fittings, and thin flat 20-centimeter drip-tape laterals; any roll is tiny and optional",4:"real flexible collapsible yarn-reinforced layflat water-transfer hose beside a cultivated field, correctly connected to thin flat 20-centimeter drip tape; any drip-tape roll is tiny and optional",5:"real smooth non-reinforced flexible collapsible layflat water-transfer hose beside a cultivated field, correctly connected to thin flat 20-centimeter drip tape; any drip-tape roll is tiny and optional"}
STRICT_PRODUCT_RULES=("The supplied reference teaches only the physical shape of a real drip-tape roll. The roll is black flat tape wound on a plain simple core and must sit naturally on bare soil beside a cultivated row. Never depict it as a white cylindrical package, branded carton, paper spool, bucket, drum, canister, retail package, or giant central product pedestal. Never invent AFP branding or any label on the roll. For the hero image the agricultural field is the main subject and any roll occupies at most 20 percent of the frame near a side or lower corner. For technical images any roll is secondary and never obscures equipment. Drip tape is thin flat black polyethylene tape, not a round pipe, garden hose, corrugated hose, cable, rigid perforated strip, or thick coil. A polyethylene main pipe is round black agricultural pipe. Reinforced layflat hose is collapsible with credible yarn reinforcement; non-reinforced layflat hose is smooth and collapsible, never corrugated. Show hydraulically credible fittings and scale. Use only scene-required products. No Persian or Arabic text. No letters, words, digits, labels, captions, signs, packaging, logos, brands, or generated watermarks. The pipeline adds the one approved English watermark afterward.")
def reference_images(kind):
 if kind not in SCENES:raise ValueError(f'Unknown image kind: {kind}')
 return [DRIP_TAPE_ROLL_REFERENCE]
def image_prompt(item,kind):return "Photorealistic documentary agricultural photograph in Iran, realistic scale and natural daylight. "+SCENES[kind]+". "+STRICT_PRODUCT_RULES+" Clean 16:9 composition, no landmark and no unverifiable local claim."
def install(backend):backend.SCENES=SCENES;backend.REFERENCE_IMAGES=REFERENCE_IMAGES;backend.image_prompt=image_prompt
